### ISSUE TITLE
Random changes in  output mode

### ISSUE THREAD

**Issue by alexDF-79** [persuader72/silla-prism-integration#3]
I noticed that when I put the Silla in pause, randomly the wall box state is changed to waiting, then to solar and it starts to charge the car, even if I wanted the wall box to stay in pause . 
Is there a reason for that? Maybe some automation hidden somewhere? 
Thanks, here the log for which I do not have an answer 

Prism Current port output mode changed to solar
9:04:37 PM - 28 minutes ago
Prism Current limit changed to 32.0
9:04:37 PM - 28 minutes ago
Prism Wallbox current state changed to waiting
9:04:37 PM - 28 minutes ago

**Comment by persuader72** [comment]
No there are not hidden automations, the sensor are loaded directly with te states from the mqtt broker. An commands are sent to the mqtt broker trough setting the states of configuration entities.

I see in past that when the solar mode is used together with the load balancing can be quite tricky understand the reason of the pause. When the port mode state is in "Pause"  can be so because the user put the Prism in pause mode or because the Solar mode put it in pause for absence of solar power.  In the latter case the solar mode will restore the charging when use sun is enugh.

Anyway to be sure you can log your mqtt broker and look for call to this topics **prism/1/command/set_mode**, **command/set_current_user** or **prism/1/command/set_current_limit** those are the topics used internally by the integration to change  the Prism port state, but always only when the user or an external automation require  it.

**Comment by alexDF-79** [comment]
Many thanks. I will continue to explore the best way to manage it.
